# Generated by Django 5.1.2 on 2024-10-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumedetails', '0003_alter_admin_managers_alter_admin_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
